language: php
dist: bionic

services:
  - mysql

notifications:
  email: false

# Safelist (only test pushes/merges with these branches)
branches:
  only:
    - trunk
    - develop

cache:
  directories:
    - $HOME/.composer/cache
  npm: true

# Test supported versions of PHP, WP and WC and the WC master branch.
php:
  - 7.3
  - 7.4

env:
  global:
    - WP_DIR=/tmp/wordpress
    - WP_CORE_DIR="${WP_DIR}/src"
    - WP_TESTS_DIR="${WP_DIR}/tests/phpunit"
    - WP_LATEST=5.8
    - WC_LATEST=trunk
  matrix:
    - WP_VERSION="${WP_LATEST}" WC_VERSION="${WC_LATEST}"
    - WP_VERSION="${WP_LATEST}" WC_VERSION=5.4
    - WP_VERSION=5.7 WC_VERSION=5.4
    - WP_VERSION=5.6 WC_VERSION=5.4

# Additional tests
matrix:
  fast_finish: true
  include:
    - name: "JS unit tests"
      language: node_js # Takes version from `.nvmrc`, runs `npm ci` automatically.
      env: WP_VERSION="${WP_LATEST}" WC_VERSION="${WC_LATEST}" WP_TRAVISCI=jest WP_MULTISITE=0
      script: npm run test-unit
    - name: "Coding standard check"
      php: 7.4
      env: WP_VERSION="${WP_LATEST}" WC_VERSION="${WC_LATEST}" WP_TRAVISCI=cs WP_MULTISITE=0
      script: npm run lint
    - name: "Bundle size"
      php: 7.4
      env: WP_VERSION="${WP_LATEST}" WC_VERSION="${WC_LATEST}" WP_TRAVISCI=bs WP_MULTISITE=0 CI_BRANCH_BASE="${TRAVIS_BRANCH}"
      # We run the production build, to watch also .zip size.
      script:
        - echo 'Build production bundles' && echo -en "travis_fold:start:Build\r"
        - npm run build
        - echo -en 'travis_fold:end:Build\r'
        - npx bundlewatch

before_install:
  - if [[ "${WP_TRAVISCI}" != "jest" ]]; then composer self-update --1; fi

install:
  - nvm install

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - if [[ "${WP_TRAVISCI}" != "jest" ]]; then composer install; fi
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - npm ci
  - if [[ "${WP_TRAVISCI}" != "bs" ]]; then npm run dev; fi

script:
  - composer test-unit
