name: E2E Tests

on:
  push:
    branches:
      - trunk
      - develop
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  E2ETests:
    name: E2E Tests
    runs-on: ubuntu-latest
    env:
      FORCE_COLOR: 2
    steps:
      # Needed for Ubuntu 20.04.
      - name: Kill mono to free 8084
        run: |
          sudo killall mono

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Prepare PHP
        uses: woocommerce/grow/prepare-php@actions-v1
        with:
          install-deps: "no"

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"
          ignore-scripts: "no"

      - name: Build production bundle
        run: |
          echo "::group::Build log"
          npm run build
          echo "::endgroup::"

      - name: Start docker container
        run: |
          npm run docker:up
          sleep 10

      - name: Run tests
        env:
            WC_E2E_SCREENSHOTS: 1
        run: |
          npm run test:e2e

      - name: Archive e2e test screenshots
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
            name: e2e-screenshots
            path: tests/e2e/screenshots
            if-no-files-found: ignore
            retention-days: 5
