name: JavaScript and CSS Linting

on:
  push:
    branches:
      - trunk
      - develop
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml
  pull_request:
    paths:
      - "**.js"
      - "**.scss"
      - .github/workflows/js-css-linting.yml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  FORCE_COLOR: 2

jobs:
  JSLintingCheck:
    name: Lint JavaScript
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/eslint-annotation@actions-v1-pre

      - name: Lint JavaScript and annotate linting errors
        run: npm run lint:js -- --quiet --format ./eslintFormatter.cjs


  CSSLintingCheck:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Prepare node
        uses: woocommerce/grow/prepare-node@actions-v1
        with:
          node-version-file: ".nvmrc"

      - name: Prepare annotation formatter
        uses: woocommerce/grow/stylelint-annotation@actions-v1-pre

      - name: Lint CSS and annotate linting errors
        run: npm run lint:css -- --custom-formatter ./stylelintFormatter.cjs
